{"name": "测试用例标题1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test.Testcase object at 0x0358CFB8>\n\n    @allure.title('测试用例标题1')\n    @allure.description('这是测试用例用例1的描述信息')\n    def test_case01(self):\n    \n        print('执行用例01.......')\n    \n>       assert 0  # 断言失败\nE       assert 0\n\ntestCase\\test.py:23: AssertionError"}, "description": "这是测试用例用例1的描述信息", "start": 1625133637048, "stop": 1625133637049, "uuid": "9230aa03-2bf7-4f01-bcce-6a33cc4e14a9", "historyId": "9a0b11c2437cbc89147d7c380b2f41d1", "testCaseId": "5da4694bc8c02f9d51b6600c766b0d90", "fullName": "testCase.test.Testcase#test_case01", "labels": [{"name": "parentSuite", "value": "testCase"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "Testcase"}, {"name": "host", "value": "XSD-20190315NRK"}, {"name": "thread", "value": "3544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.test"}]}